import {describe,it} from 'node:test';
import assert from 'node:assert/strict';
import {blankState,applyAction,recommendations,progress,metrics,ideas} from '../lib/model.ts';
const now='2026-09-06T09:00:00.000Z';
const start=()=>applyAction(blankState(now),{type:'journey.start',payload:{name:'Test learner',goal:'Understand systems',target:1500,project:'tcp'}},now);
describe('Evidence and saved progress',()=>{
it('starts a clean personal journey with no fabricated achievements',()=>{const s=start();assert.equal(s.sessions.length,0);assert.equal(s.scores.length,0);assert.equal(metrics(s).milestones,0);assert.equal(progress(s.projects[0]),0);assert.equal(s.profile.onboarded,true)});
it('requires prerequisite milestones and evidence before advancing',()=>{const s=start();assert.throws(()=>applyAction(s,{type:'milestone.complete',payload:{id:s.projects[0].id,index:2,evidence:'test'}}));assert.throws(()=>applyAction(s,{type:'milestone.complete',payload:{id:s.projects[0].id,index:0,evidence:''}}));const next=applyAction(s,{type:'milestone.complete',payload:{id:s.projects[0].id,index:0,evidence:'Documented a request path and verified each component.'}},now);assert.equal(progress(next.projects[0]),13);assert.equal(progress(s.projects[0]),0)});
it('records time independently from project completion and deduplicates retries',()=>{const s=start(),task=recommendations(s)[0];const a={type:'session.finish',payload:{id:'attempt-1',task,seconds:1920,notes:'Investigated one fragmented message.',outcome:'progress',energy:1}};const next=applyAction(s,a,now);const repeated=applyAction(next,a,now);assert.equal(repeated.sessions.length,1);assert.equal(metrics(repeated).minutes,32);assert.equal(progress(repeated.projects[0]),0)});
it('rejects impossible SAT observations',()=>{const s=start();assert.throws(()=>applyAction(s,{type:'score.add',payload:{date:'2026-09-06',source:'Test',math:801,reading:700}}));assert.throws(()=>applyAction(s,{type:'score.add',payload:{date:'2026-02-31',source:'Test',math:700,reading:700}}));assert.throws(()=>applyAction(s,{type:'practice.add',payload:{date:'2026-09-06',topic:'Algebra',section:'Math',questions:5,correct:6,minutes:10}}));assert.throws(()=>applyAction(s,{type:'profile.update',payload:{target:1555}}))});
it('resizes work without creating a catch-up backlog',()=>{const s=start(),minimal=recommendations(s,0,5);assert.equal(minimal.length,1);assert.equal(minimal[0].minutes,5);const next=applyAction(s,{type:'plan.restart',payload:{areas:['SAT']}},now);assert.equal(next.plan.length,7);assert.equal(next.plan[0].date,'2026-09-06');assert.equal(next.plan.filter(d=>d.minutes===0).length,2);assert.equal(next.plan[0].area,'SAT');assert.equal(next.projects[0].milestones.length,8)});
it('has 24 complete scoped project definitions',()=>{assert.equal(ideas.length,24);assert.equal(new Set(ideas.map(i=>i.id)).size,24);for(const i of ideas){assert.equal(i.milestones.length,8);assert.ok(i.prerequisites);assert.ok(i.architecture)}});
});
describe('FSRS adaptive review',()=>{
const mistake=()=>applyAction(start(),{type:'mistake.add',payload:{question:'Personal practice question',source:'My own notes',section:'Math',topic:'Algebra',difficulty:'Medium',answer:'3',correct:'4',explanation:'I subtracted instead of adding.',reason:'Calculation'}},now);
it('creates a new due card without fabricated review history',()=>{const s=mistake(),m=s.mistakes[0];assert.equal(m.card?.due,new Date(now).getTime());assert.equal(m.card?.reps,0);assert.equal(m.reviews?.length,0)});
it('persists the whole scheduler state and review history across JSON round trips',()=>{const s=mistake(),id=s.mistakes[0].id;const next=applyAction(s,{type:'mistake.review',payload:{id,status:'Mastered'}},now);const m=next.mistakes[0];assert.equal(m.card?.reps,1);assert.equal(m.reviews?.length,1);assert.ok(m.card!.due>new Date(now).getTime());const reread=JSON.parse(JSON.stringify(next));const reviewed=applyAction(reread,{type:'mistake.review',payload:{id,status:'Review again'}},new Date(m.card!.due).toISOString());assert.equal(reviewed.mistakes[0].card?.reps,2);assert.equal(reviewed.mistakes[0].reviews?.length,2)});
it('does not permanently remove confidently recalled mistakes',()=>{const s=mistake();const reviewed=applyAction(s,{type:'mistake.review',payload:{id:s.mistakes[0].id,status:'Mastered'}},'2025-01-01T00:00:00.000Z');assert.equal(recommendations(reviewed)[0].area,'SAT')});
});
