'use client';
import React,{createContext,useContext,useState} from 'react';
import {ArrowRight,ArrowUpRight,Check,ChevronRight,LoaderCircle,Plus,Sprout} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import type {Action,AppState,Task} from '@/lib/model';
export type AppContextType={state:AppState;demo:boolean;busy:boolean;githubConfigured:boolean;send:(action:Action)=>Promise<void>;notify:(text:string,error?:boolean)=>void;navigate:(view:string)=>void;start:(task:Task)=>void;openForm:(form:FormConfig)=>void;refresh:()=>Promise<void>;revision:number};
export const AppContext=createContext<AppContextType>(null!);
export const useApp=()=>useContext(AppContext);
export function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[];label:string}){return <Select value={value} onValueChange={v=>v!==null&&onChange(String(v))}><SelectTrigger className="choice" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select>}
export function PageHeading({eyebrow,title,subtitle,children}:{eyebrow:string;title:string;subtitle:string;children?:React.ReactNode}){return <div className="view-heading"><div><div className="eyebrow"><span className="live-dot"/>{eyebrow}</div><h1>{title}</h1><p>{subtitle}</p></div>{children}</div>}
export function Empty({title,text,action,onClick}:{title:string;text:string;action?:string;onClick?:()=>void}){return <div className="empty-state"><span className="empty-icon"><Sprout size={26}/></span><h3>{title}</h3><p>{text}</p>{action&&<button className="primary" onClick={onClick}>{action}<ArrowRight size={16}/></button>}</div>}
export function Meter({value,label,end}:{value:number;label:string;end?:string}){return <div className="meter"><div className="progress-label"><span>{label}</span><strong>{end??value+'%'}</strong></div><Progress value={value}/></div>}
export function Stat({label,value,note,color}:{label:string;value:string|number;note?:string;color?:string}){return <div className={'stat-block '+(color||'')}><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
export function External({href,children}:{href:string;children:React.ReactNode}){return <a className="external" href={href} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={14}/></a>}
export type Field={name:string;label:string;type?:string;options?:string[];value?:string|number;required?:boolean;placeholder?:string;min?:number;max?:number;step?:number;help?:string};
export type FormConfig={title:string;description:string;fields:Field[];submit:string;onSubmit:(data:Record<string,unknown>)=>Promise<void>};
export function EntryForm({config,onClose}:{config:FormConfig;onClose:()=>void}){const [values,setValues]=useState<Record<string,string>>(()=>Object.fromEntries(config.fields.map(f=>[f.name,String(f.value??f.options?.[0]??'')])));const [saving,setSaving]=useState(false),[error,setError]=useState('');return <Dialog open onOpenChange={v=>!v&&!saving&&onClose()}><DialogContent className="app-dialog form-dialog"><DialogHeader><DialogTitle>{config.title}</DialogTitle><DialogDescription>{config.description}</DialogDescription></DialogHeader><form onSubmit={async e=>{e.preventDefault();setSaving(true);setError('');try{await config.onSubmit(values);onClose()}catch(e){setError(e instanceof Error?e.message:'Please try again.')}finally{setSaving(false)}}}><div className="form-fields">{config.fields.map(f=><label className={'field '+(f.type==='textarea'?'full':'')} key={f.name}><span>{f.label}{f.required!==false&&<i> *</i>}</span>{f.options?<Choice label={f.label} value={values[f.name]} onChange={v=>setValues({...values,[f.name]:v})} options={f.options}/>:f.type==='textarea'?<textarea required={f.required!==false} maxLength={f.max||10000} value={values[f.name]} placeholder={f.placeholder} onChange={e=>setValues({...values,[f.name]:e.target.value})}/>:<input type={f.type||'text'} value={values[f.name]} required={f.required!==false} min={f.min} max={f.max} step={f.step} maxLength={f.type==='number'?undefined:f.max||5000} placeholder={f.placeholder} onChange={e=>setValues({...values,[f.name]:e.target.value})}/>} {f.help&&<small>{f.help}</small>}</label>)}</div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="dialog-actions"><button className="quiet-button" type="button" onClick={onClose} disabled={saving}>Cancel</button><button className="primary" disabled={saving}>{saving?<LoaderCircle size={16} className="spin"/>:<Check size={16}/>} {saving?'Saving…':config.submit}</button></div></form></DialogContent></Dialog>}
export function dateLabel(d:string){return new Date(d.length===10?d+'T12:00:00':d).toLocaleDateString('en-US',{month:'short',day:'numeric'})}
export function Heatmap({sessions}:{sessions:AppState['sessions']}){const today=new Date();today.setHours(12,0,0,0);const days=Array.from({length:84},(_,i)=>{const d=new Date(today);d.setDate(d.getDate()-83+i);const key=d.toLocaleDateString('en-CA');const matching=sessions.filter(s=>new Date(s.date).toLocaleDateString('en-CA')===key);return{date:key,min:Math.round(matching.reduce((a,s)=>a+s.seconds,0)/60)}});return <div className="heatmap-wrap"><div className="heatmap" role="img" aria-label={'Last 12 weeks of focus activity. '+days.filter(d=>d.min>0).length+' days with recorded work.'}>{days.map(d=><span key={d.date} tabIndex={0} title={dateLabel(d.date)+': '+d.min+' focused minutes'} aria-label={dateLabel(d.date)+': '+d.min+' focused minutes'} className={'heat-cell heat-'+(d.min===0?0:d.min<20?1:d.min<40?2:d.min<60?3:4)}/>)}</div><div className="heat-legend"><span>The last 12 weeks · your effort stays here</span><span>Less {Array.from({length:5},(_,i)=><i key={i} className={'heat-'+i}/>)} More</span></div></div>}
