import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import { blankState, type AppState } from './model';
export function db(){if(!env.DB)throw new Error('Storage is unavailable. Please try again.');return env.DB;}
export function runtime(name:string):string {return String((env as unknown as Record<string,unknown>)[name]||'')}
export async function user(){const u=await getChatGPTUser();if(!u)throw new ApiError('Sign in to save your personal journey.',401);return u.userId;}
export class ApiError extends Error{constructor(message:string,public status=400){super(message)}}
export function json(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})}
export function fail(error:unknown){return json({error:error instanceof ApiError?error.message:error instanceof Error&&error.message.length<250?error.message:'Something could not be saved. Please try again.'},error instanceof ApiError?error.status:400)}
export function sameOrigin(request:Request){const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)throw new ApiError('Please make this request from Future Builder.',403);if(request.headers.get('sec-fetch-site')==='cross-site')throw new ApiError('Cross-site request rejected.',403);}
export async function body(request:Request){if(!request.headers.get('content-type')?.includes('application/json'))throw new ApiError('Expected JSON data.');if(Number(request.headers.get('content-length'))>200000)throw new ApiError('This request is too large.',413);const text=await request.text();if(text.length>200000)throw new ApiError('This request is too large.',413);const p=JSON.parse(text);if(!p||typeof p!=='object'||Array.isArray(p))throw new ApiError('Invalid request.');return p as Record<string,unknown>}
export async function readState(uid:string){const row=await db().prepare('SELECT state, revision FROM journeys WHERE user_id = ?').bind(uid).first<{state:string;revision:number}>();return row?{state:JSON.parse(row.state) as AppState,revision:row.revision}:{state:blankState(),revision:0};}
export async function saveState(uid:string,state:AppState,revision:number){const now=new Date().toISOString();if(revision===0){const result=await db().prepare('INSERT OR IGNORE INTO journeys (user_id,state,revision,updated) VALUES (?,?,1,?)').bind(uid,JSON.stringify(state),now).run();if(result.meta.changes)return 1;}const result=await db().prepare('UPDATE journeys SET state = ?, revision = revision + 1, updated = ? WHERE user_id = ? AND revision = ?').bind(JSON.stringify(state),now,uid,revision).run();if(!result.meta.changes)throw new ApiError('Your journey changed in another tab. Reload it before saving again.',409);return revision+1;}
export function safeOrigin(request:Request){const configured=runtime('APP_ORIGIN');const origin=configured||'https://future-builder.aviadcoh.chatgpt.site';if(origin.startsWith('https://'))return origin;throw new ApiError('The application origin is not configured.',503)}
export async function gh(path:string,token:string){const r=await fetch('https://api.github.com'+path,{headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'FutureBuilder'},signal:AbortSignal.timeout(15000)});if(!r.ok)throw new ApiError(r.status===403?'GitHub’s request limit was reached. Try again later.':r.status===401?'Please reconnect GitHub.':'GitHub could not return this repository data.',502);return r.json() as Promise<any>}
const b64=(v:Uint8Array)=>btoa(String.fromCharCode(...v)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=/g,'');
export const randomToken=()=>b64(crypto.getRandomValues(new Uint8Array(32)));
export const challenge=async(s:string)=>b64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))));
async function key(){const secret=runtime('TOKEN_ENCRYPTION_KEY');if(secret.length<32)throw new ApiError('GitHub connection needs a server encryption key.',503);return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',new TextEncoder().encode(secret)),{name:'AES-GCM'},false,['encrypt','decrypt']);}
export async function encrypt(value:string){const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},await key(),new TextEncoder().encode(value));return b64(iv)+'.'+b64(new Uint8Array(data));}
export async function decrypt(value:string){const decode=(s:string)=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));const [iv,data]=value.split('.');return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(iv)},await key(),decode(data)));}
